services:
  postgres:
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: discord
      POSTGRES_DB: discord
  redis:
    image: redis
    ports:
      - 6379:6379
  app:
    image: bendeez/discord-clone:app
    ports:
      - 8000:80
  test:
    image: bendeez/discord-clone:test
    ports:
      - 3000:3000
